image: maven:latest

cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

deploy_stage:
  stage: deploy
  only:
    - develop
  script:
    - apt-get update && apt-get install -y -qq sshpass
    - export SSHPASS=$USER_PASS
    - cd target/
    - sshpass -e scp -o stricthostkeychecking=no -r . $USER_NAME@$IP_ADDRESS:/opt/groovy/bots/canary
    - sshpass -e ssh -t $USER_NAME@$IP_ADDRESS "sudo /opt/groovy/groovy.sh canary restart"
