image: maven:latest

stages:
  - clean
  - package

clean:
  stage: clean
  script:
    - mvn $MAVEN_CLI_OPTS clean

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package
    artifacts:
      paths:
      - target/*.jar
      expire_in: 1 week
