version: '3'
services:
    lavalink:
      image: fredboat/lavalink:feature_close-events-
      ports:
        - "8099:2333"
      restart: always
      env_file:
        - lavalink.env
      networks:
        - backend
    discord-bot:
      build: .
      depends_on:
        - "lavalink"
      networks:
        - backend
      volumes:
        - "$PWD:/opt/groovy/"
      command: ["./wait-for-lavalink.sh", "java", "-jar", "groovybot.jar", "debug"]
networks:
    backend:


